// automatically generated by the FlatBuffers compiler, do not modify

package com.dimitrismantas.torch.core.utils.serialization.graph;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DeserializedGraph extends Table {
  public static void ValidateVersion() {
    Constants.FLATBUFFERS_22_10_26();
  }

  public static DeserializedGraph getRootAsDeserializedGraph(ByteBuffer _bb) {
    return getRootAsDeserializedGraph(_bb, new DeserializedGraph());
  }

  public static DeserializedGraph getRootAsDeserializedGraph(ByteBuffer _bb, DeserializedGraph obj) {
    _bb.order(ByteOrder.LITTLE_ENDIAN);
    return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
  }

  public void __init(int _i, ByteBuffer _bb) {
    __reset(_i, _bb);
  }

  public DeserializedGraph __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public DeserializedVertex vertices(int j) {
    return vertices(new DeserializedVertex(), j);
  }

  public DeserializedVertex vertices(DeserializedVertex obj, int j) {
    int o = __offset(4);
    return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
  }

  public int verticesLength() {
    int o = __offset(4);
    return o != 0 ? __vector_len(o) : 0;
  }

  public DeserializedVertex.Vector verticesVector() {
    return verticesVector(new DeserializedVertex.Vector());
  }

  public DeserializedVertex.Vector verticesVector(DeserializedVertex.Vector obj) {
    int o = __offset(4);
    return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
  }

  public static int createDeserializedGraph(FlatBufferBuilder builder,
      int verticesOffset) {
    builder.startTable(1);
    DeserializedGraph.addVertices(builder, verticesOffset);
    return DeserializedGraph.endDeserializedGraph(builder);
  }

  public static void startDeserializedGraph(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addVertices(FlatBufferBuilder builder, int verticesOffset) { builder.addOffset(0, verticesOffset, 0); }
  public static int createVerticesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startVerticesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endDeserializedGraph(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishDeserializedGraphBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedDeserializedGraphBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DeserializedGraph get(int j) { return get(new DeserializedGraph(), j); }
    public DeserializedGraph get(DeserializedGraph obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

