// automatically generated by the FlatBuffers compiler, do not modify

package com.dimitrismantas.torch.core.graph;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Graph extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_1_21(); }
  public static Graph getRootAsGraph(ByteBuffer _bb) { return getRootAsGraph(_bb, new Graph()); }
  public static Graph getRootAsGraph(ByteBuffer _bb, Graph obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Graph __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vertex vertices(int j) { return vertices(new Vertex(), j); }
  public Vertex vertices(Vertex obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int verticesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public Vertex.Vector verticesVector() { return verticesVector(new Vertex.Vector()); }
  public Vertex.Vector verticesVector(Vertex.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createGraph(FlatBufferBuilder builder,
      int verticesOffset) {
    builder.startTable(1);
    Graph.addVertices(builder, verticesOffset);
    return Graph.endGraph(builder);
  }

  public static void startGraph(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addVertices(FlatBufferBuilder builder, int verticesOffset) { builder.addOffset(0, verticesOffset, 0); }
  public static int createVerticesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startVerticesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endGraph(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishGraphBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedGraphBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Graph get(int j) { return get(new Graph(), j); }
    public Graph get(Graph obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

